
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install texlive-full cm-super default-jre imagemagick wget gnuplot ghostscript poppler-utils  graphviz locales locales-all     && wget -q -O plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2024.6/plantuml-1.2024.6.jar && sudo sed -i '/ru_RU.UTF-8/s/^# //g' /etc/locale.gen && sudo locale-gen

      - name: Compile LaTeX document
        run: ./.github/scripts/build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: main.pdf
